# Generated by Django 4.1.1 on 2022-10-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='imagenes')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Cc', models.CharField(max_length=11, unique=True)),
                ('Phone', models.CharField(max_length=13)),
                ('Direction', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=4)),
                ('Eps', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('meets_the_profile', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Empleados',
            },
        ),
    ]
