# Generated by Django 4.1.1 on 2022-10-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Cc', models.CharField(max_length=11, unique=True)),
                ('Phone', models.CharField(max_length=13)),
                ('Direction', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=4)),
                ('Eps', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Occupation', models.CharField(max_length=100)),
                ('hour_entry_finish', models.DateTimeField(max_length=100)),
                ('Doctor_concept', models.TextField(max_length=1000)),
            ],
        ),
    ]
