# Generated by Django 4.1.1 on 2022-10-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Cc', models.CharField(max_length=11, unique=True)),
                ('Phone', models.CharField(max_length=13)),
                ('Direction', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=15)),
                ('Professional_card', models.CharField(max_length=30)),
                ('Specialization', models.CharField(max_length=100)),
            ],
        ),
    ]
